// Generated by tools/gen_tables.py from tools/editor_models.json - do not edit.
// FX models of the Nano Cortex with their parameters, as defined in the Nano Cortex Editor.
// The type is the varint value the Nano uses for the model (StateResponse 48-52, FxTypeValue).
#pragma once
#include <stdint.h>

typedef enum { NANO_PARAM_RANGE, NANO_PARAM_ENUM } nano_param_kind_t;

typedef struct {
    const char *name;
    uint8_t kind;
    float min, max, step;      // range parameters
    const char *unit;
    int8_t decimals;
    uint8_t option_count;      // enum parameters
    const char *options;       // enum options separated by "\n" (LVGL dropdown format)
} nano_param_t;

typedef struct {
    uint32_t type;
    const char *name;
    uint8_t icon;              // NANO_ICON_*
    uint32_t color;
    int8_t mix_param;          // index of the "Mix" parameter, -1 if none
    uint8_t param_count;
    const nano_param_t *params;
    const uint8_t *order;      // display order of the parameters (indexes), NULL = as defined
} nano_fx_model_t;

enum {
    NANO_ICON_OVERDRIVE,
    NANO_ICON_BASS_OVERDRIVE,
    NANO_ICON_FUZZ,
    NANO_ICON_COMPRESSOR,
    NANO_ICON_EQUALIZER,
    NANO_ICON_FILTER,
    NANO_ICON_WAH,
    NANO_ICON_UTILITY,
    NANO_ICON_GATE,
    NANO_ICON_DOUBLER,
    NANO_ICON_PITCH,
    NANO_ICON_MODULATION,
    NANO_ICON_DELAY,
    NANO_ICON_REVERB,
    NANO_ICON_CAPTURE,
    NANO_ICON_CAB,
    NANO_ICON_TUNER,
    NANO_ICON_COUNT
};

extern const nano_fx_model_t NANO_FX_MODELS[];
extern const unsigned NANO_FX_MODEL_COUNT;

// Models available per FX slot (Pre FX 1, Pre FX 2, Post FX 1-3), in the editor's order.
extern const uint32_t *const NANO_SLOT_MODELS[5];
extern const uint8_t NANO_SLOT_MODEL_COUNT[5];
