// Generated by tools/gen_tables.py from tools/editor_models.json - do not edit.
#include "fx_models.h"
#include <stddef.h>

static const nano_param_t m18_params[] = {
    { "Gain", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Tone", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m13_params[] = {
    { "Gain", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Level", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m6_params[] = {
    { "Gain", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Bass", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Treble", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m3007_params[] = {
    { "Gain", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Bass", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Treble", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m23_params[] = {
    { "Gain", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Bass", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Treble", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m22_params[] = {
    { "Fuzz", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Pickup", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "HB\nSingle" },
    { "Pickup Level", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m27_params[] = {
    { "Overdrive", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Tone", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Level", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m3000_params[] = {
    { "Drive", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Growl", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Midboost", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Tone", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Level", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Blend", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m3_params[] = {
    { "Gain", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m2_params[] = {
    { "Drive", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Peak", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "LP\nHP" },
    { "Tone", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m4_params[] = {
    { "Distortion", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Filter", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Volume", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
};
static const nano_param_t m16001_params[] = {
    { "Noise Reduction", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m4005_params[] = {
    { "65Hz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "125Hz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "250Hz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "500hz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "1kHz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "2kHz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "4kHz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "8kHz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "16kHz", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "HPF", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "LPF", NANO_PARAM_RANGE, 1000.0f, 16000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
};
static const nano_param_t m4003_params[] = {
    { "HPF Slope", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 9, "Flat\n-6\n-12\n-18\n-24\n-30\n-36\n-42\n-48" },
    { "HPF Freq", NANO_PARAM_RANGE, 20.0f, 20000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "LPF Slope", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 9, "Flat\n-6\n-12\n-18\n-24\n-30\n-36\n-42\n-48" },
    { "LPF Freq", NANO_PARAM_RANGE, 20.0f, 20000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
};
static const nano_param_t m4001_params[] = {
    { "1 Gain", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "1 Freq", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "1 Q", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "1 Type", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 5, "Peak\nHi Pass\nLo Pass\nHi Shelf\nLo Shelf" },
    { "1 Active", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "2 Gain", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "2 Freq", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "2 Q", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "2 Type", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 5, "Peak\nHi Pass\nLo Pass\nHi Shelf\nLo Shelf" },
    { "2 Active", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "3 Gain", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "3 Freq", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "3 Q", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "3 Type", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 5, "Peak\nHi Pass\nLo Pass\nHi Shelf\nLo Shelf" },
    { "3 Active", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
};
static const nano_param_t m16002_params[] = {
    { "Threshold", NANO_PARAM_RANGE, -90.0f, 0.0f, 0.1f, "dB", 1, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 1000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Hold", NANO_PARAM_RANGE, 1.0f, 2000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 2.0f, 5000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Range", NANO_PARAM_RANGE, -90.0f, -6.0f, 0.1f, "dB", 1, 0, NULL },
};
static const nano_param_t m16006_params[] = {
    { "Level", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Curve", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Linear\nLog" },
};
static const nano_param_t m9012_params[] = {
    { "Wah", NANO_PARAM_RANGE, 0.0f, 1.0f, 0.01f, "", 2, 0, NULL },
};
static const nano_param_t m9010_params[] = {
    { "Wah", NANO_PARAM_RANGE, 0.0f, 1.0f, 0.01f, "", 2, 0, NULL },
};
static const nano_param_t m9014_params[] = {
    { "Wah", NANO_PARAM_RANGE, 0.0f, 1.0f, 0.01f, "", 2, 0, NULL },
};
static const nano_param_t m9013_params[] = {
    { "Wah", NANO_PARAM_RANGE, 0.0f, 1.0f, 0.01f, "", 2, 0, NULL },
};
static const nano_param_t m24006_params[] = {
    { "Sens", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 1000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Decay", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "LP/BP/HP", NANO_PARAM_RANGE, -1.0f, 1.0f, 0.01f, "", 2, 0, NULL },
    { "Level", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Freq", NANO_PARAM_RANGE, 20.0f, 20000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Freq Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Reso", NANO_PARAM_RANGE, 1.0f, 10.0f, 0.01f, "", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m24001_params[] = {
    { "Sensitivity", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 1000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Decay", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Color", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Intensity", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Blend", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Trig Detection", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Down\nUp" },
    { "Trigger Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "Off\nFull\n1/2" },
    { "Filter Cutoff", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 4, "Low\nA\nB\nHigh" },
    { "Filter Type", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "Lowpass\nBandpass\nHighpass" },
    { "Level", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m5001_params[] = {
    { "Input", NANO_PARAM_RANGE, -48.0f, 0.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 5, "4\n8\n12\n20\nAll" },
    { "Attack", NANO_PARAM_RANGE, 0.02f, 0.8f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 0.06f, 1.1f, 0.01f, "s", 2, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m5007_params[] = {
    { "Threshold", NANO_PARAM_RANGE, -60.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_RANGE, 2.0f, 20.0f, 0.01f, "", 2, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 250.0f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 50.0f, 1200.0f, 1.0f, "ms", 0, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m5004_params[] = {
    { "Threshold", NANO_PARAM_RANGE, -60.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "2\n4\n10" },
    { "Attack", NANO_PARAM_RANGE, 0.1f, 30.0f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 0.01f, 1.2f, 0.01f, "s", 2, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m5005_params[] = {
    { "Threshold", NANO_PARAM_RANGE, -60.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_RANGE, 2.0f, 10.0f, 0.01f, "", 2, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 250.0f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 50.0f, 1200.0f, 1.0f, "ms", 0, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m18001_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Semitones", NANO_PARAM_RANGE, -12.0f, 12.0f, 1.0f, "Sem", 0, 0, NULL },
    { "Pitch Fine", NANO_PARAM_RANGE, -100.0f, 100.0f, 1.0f, "Cent", 0, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 2000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 200.0f, 19900.0f, 1.0f, "Hz", 0, 0, NULL },
};
static const nano_param_t m16011_params[] = {
    { "Spread", NANO_PARAM_RANGE, 3.0f, 60.0f, 0.01f, "ms", 2, 0, NULL },
    { "Dry Level", NANO_PARAM_RANGE, -40.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "FX Level", NANO_PARAM_RANGE, -40.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
};
static const nano_param_t m5012_params[] = {
    { "Input", NANO_PARAM_RANGE, -48.0f, 0.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 5, "4\n8\n12\n20\nAll" },
    { "Attack", NANO_PARAM_RANGE, 0.02f, 0.8f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 0.06f, 1.1f, 0.01f, "s", 2, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m5015_params[] = {
    { "Threshold", NANO_PARAM_RANGE, -60.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_RANGE, 2.0f, 20.0f, 0.01f, "", 2, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 250.0f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 50.0f, 1200.0f, 1.0f, "ms", 0, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m5013_params[] = {
    { "Threshold", NANO_PARAM_RANGE, -60.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "2\n4\n10" },
    { "Attack", NANO_PARAM_RANGE, 0.1f, 30.0f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 0.01f, 1.2f, 0.01f, "s", 2, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m5014_params[] = {
    { "Threshold", NANO_PARAM_RANGE, -60.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Ratio", NANO_PARAM_RANGE, 2.0f, 10.0f, 0.01f, "", 2, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 250.0f, 0.01f, "ms", 2, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 50.0f, 1200.0f, 1.0f, "ms", 0, 0, NULL },
    { "Makeup", NANO_PARAM_RANGE, -48.0f, 48.0f, 0.01f, "dB", 2, 0, NULL },
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m7024_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Rate", NANO_PARAM_RANGE, 0.0f, 100.0f, 1.0f, "%", 0, 0, NULL },
    { "Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Type", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "CE2-C\nCE1-C\nCE1-V" },
    { "Width", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 14, "1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m7024_order[] = { 0, 1, 6, 7, 2, 3, 4, 5 };
static const nano_param_t m7027_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 10, "1\n2\n3\n4\n1+2\n1+3\n1+4\n2+3\n2+4\n3+4" },
    { "Mode Type", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "S\nSDD-320" },
    { "Drive", NANO_PARAM_RANGE, 0.0f, 100.0f, 1.0f, "%", 0, 0, NULL },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
};
static const nano_param_t m7023_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Rate", NANO_PARAM_RANGE, 0.2f, 3.0f, 0.01f, "Hz", 2, 0, NULL },
    { "Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Width", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 11, "1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m7023_order[] = { 0, 1, 5, 6, 2, 3, 4 };
static const nano_param_t m7022_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Speed", NANO_PARAM_RANGE, 0.0f, 100.0f, 1.0f, "%", 0, 0, NULL },
    { "Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "CHO1\nCHO2" },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 14, "1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m7022_order[] = { 0, 1, 5, 6, 2, 3, 4 };
static const nano_param_t m7021_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Manual", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Width", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Speed", NANO_PARAM_RANGE, 0.0f, 100.0f, 1.0f, "%", 0, 0, NULL },
    { "Regen", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 14, "1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m7021_order[] = { 0, 1, 2, 3, 6, 7, 4, 5 };
static const nano_param_t m7028_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Speed", NANO_PARAM_RANGE, 0.0f, 100.0f, 1.0f, "%", 0, 0, NULL },
    { "Type", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "90\n45" },
    { "Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Block\nScript" },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 17, "1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m7028_order[] = { 0, 1, 5, 6, 2, 3, 4 };
static const nano_param_t m7029_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Vibe", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Speed", NANO_PARAM_RANGE, 0.0f, 100.0f, 1.0f, "%", 0, 0, NULL },
    { "Level", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Output", NANO_PARAM_RANGE, -12.0f, 12.0f, 0.1f, "dB", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 14, "1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m7029_order[] = { 0, 1, 2, 6, 7, 3, 4, 5 };
static const nano_param_t m7004_params[] = {
    { "Rate", NANO_PARAM_RANGE, 0.1f, 20.0f, 0.1f, "Hz", 1, 0, NULL },
    { "Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Waveform", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 5, "Sine\nTriangle\nSquare\nSaw Up\nSaw Dn" },
    { "Duty Cycle", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Width", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Smoothing", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "LFO Active", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Fade In", NANO_PARAM_RANGE, 1.0f, 5000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Fade Out", NANO_PARAM_RANGE, 1.0f, 5000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Boost", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 17, "1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m7004_order[] = { 0, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const nano_param_t m6010_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Feedback", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 1000.0f, 16000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Ping Pong", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Delay Time", NANO_PARAM_RANGE, 200.0f, 1100.0f, 0.1f, "ms", 1, 0, NULL },
    { "Mod Rate", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "Hz", 1, 0, NULL },
    { "Mod Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Width", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Drive", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 14, "1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m6010_order[] = { 0, 1, 2, 3, 4, 10, 11, 5, 6, 7, 8, 9 };
static const nano_param_t m6015_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Tap Preset", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 9, "1\n2\n3\n4\n4 Alt\n5\n5 Alt\n6\n6 Alt" },
    { "Delay Time", NANO_PARAM_RANGE, 27.0f, 2000.0f, 0.01f, "ms", 2, 0, NULL },
    { "Feedback", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Diffusion", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 1000.0f, 16000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Mod Rate", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "Hz", 1, 0, NULL },
    { "Mod Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Vintage Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 21, "1/64T\n1/64\n1/32T\n1/64D\n1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m6015_order[] = { 0, 1, 10, 11, 2, 3, 4, 5, 6, 7, 8, 9 };
static const nano_param_t m6011_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Feedback", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 1000.0f, 16000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Ping Pong", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Delay Time", NANO_PARAM_RANGE, 7.0f, 6000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Mod Rate", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "Hz", 1, 0, NULL },
    { "Mod Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Width", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Dyn Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Dyn Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "Off\nDuck\nGate" },
    { "Threshold", NANO_PARAM_RANGE, -65.0f, -10.0f, 0.1f, "dB", 1, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 2000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 1.0f, 2000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Knee", NANO_PARAM_RANGE, 1.0f, 20.0f, 0.01f, "dB", 2, 0, NULL },
    { "Feedback Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 21, "1/64T\n1/64\n1/32T\n1/64D\n1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m6011_order[] = { 0, 1, 2, 3, 4, 16, 17, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
static const nano_param_t m6012_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Delay Time L", NANO_PARAM_RANGE, 7.0f, 6000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Feedback L", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "X-Feedback", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Delay Time R", NANO_PARAM_RANGE, 7.0f, 6000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Feedback R", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 1000.0f, 16000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Mod Rate", NANO_PARAM_RANGE, 0.1f, 10.0f, 0.1f, "Hz", 1, 0, NULL },
    { "Mod Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Link FBack", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Dyn Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Dyn Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "Off\nDuck\nGate" },
    { "Threshold", NANO_PARAM_RANGE, -65.0f, -10.0f, 0.1f, "dB", 1, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 2000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 1.0f, 2000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Knee", NANO_PARAM_RANGE, 1.0f, 20.0f, 0.01f, "dB", 2, 0, NULL },
    { "Feedback Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Sync L", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note L", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 21, "1/64T\n1/64\n1/32T\n1/64D\n1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
    { "Sync R", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note R", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 21, "1/64T\n1/64\n1/32T\n1/64D\n1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m6012_order[] = { 0, 18, 19, 1, 2, 3, 20, 21, 4, 5, 10, 11, 12, 13, 14, 15, 16, 17, 6, 7, 8, 9 };
static const nano_param_t m6014_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Delay Time L", NANO_PARAM_RANGE, 20.0f, 4000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Feedback L", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "X-Feedback", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Feedback Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Reverse\nFlip" },
    { "Delay Time R", NANO_PARAM_RANGE, 20.0f, 4000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Feedback R", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Overlap", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Trig Threshold", NANO_PARAM_RANGE, -65.0f, -10.0f, 0.1f, "dB", 1, 0, NULL },
    { "Dyn Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Dyn Mode", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "Off\nDuck\nGate" },
    { "Threshold", NANO_PARAM_RANGE, -65.0f, -10.0f, 0.1f, "dB", 1, 0, NULL },
    { "Attack", NANO_PARAM_RANGE, 1.0f, 2000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Release", NANO_PARAM_RANGE, 1.0f, 2000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Knee", NANO_PARAM_RANGE, 1.0f, 20.0f, 0.01f, "dB", 2, 0, NULL },
    { "Feedback Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 1000.0f, 16000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Link FBack", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note L", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 21, "1/64T\n1/64\n1/32T\n1/64D\n1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
    { "Sync Note R", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 21, "1/64T\n1/64\n1/32T\n1/64D\n1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m6014_order[] = { 0, 19, 20, 1, 2, 3, 4, 21, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 };
static const nano_param_t m6004_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Feedback", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 80.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 800.0f, 6000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Drive", NANO_PARAM_RANGE, 0.0f, 100.0f, 1.0f, "%", 0, 0, NULL },
    { "Delay Time", NANO_PARAM_RANGE, 7.0f, 6000.0f, 1.0f, "ms", 0, 0, NULL },
    { "Wow", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Flutter", NANO_PARAM_RANGE, 0.0f, 10.0f, 0.1f, "", 1, 0, NULL },
    { "Ping Pong", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 2, "Off\nOn" },
    { "Sync Note", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 21, "1/64T\n1/64\n1/32T\n1/64D\n1/32\n1/16T\n1/32D\n1/16\n1/8T\n1/16D\n1/8\n1/4T\n1/8D\n1/4\n1/2T\n1/4D\n1/2\n1/1T\n1/2D\n1/1\n1/1D" },
};
static const uint8_t m6004_order[] = { 0, 1, 2, 3, 4, 9, 10, 5, 6, 7, 8 };
static const nano_param_t m8008_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Size", NANO_PARAM_ENUM, 0, 0, 0, "", 0, 3, "Small\nMedium\nLarge" },
    { "Pre Delay", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "ms", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 800.0f, 12000.0f, 1.0f, "Hz", 0, 0, NULL },
};
static const nano_param_t m8009_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Decay", NANO_PARAM_RANGE, 5.0f, 20.0f, 0.01f, "s", 2, 0, NULL },
    { "Pre Delay", NANO_PARAM_RANGE, 1.0f, 200.0f, 0.1f, "ms", 1, 0, NULL },
    { "Damping", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 800.0f, 8000.0f, 1.0f, "Hz", 0, 0, NULL },
};
static const nano_param_t m8003_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Decay", NANO_PARAM_RANGE, 1.0f, 10.0f, 0.01f, "s", 2, 0, NULL },
    { "Pre Delay", NANO_PARAM_RANGE, 1.0f, 100.0f, 0.1f, "ms", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 800.0f, 12000.0f, 1.0f, "Hz", 0, 0, NULL },
};
static const nano_param_t m8011_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Decay", NANO_PARAM_RANGE, 1.0f, 10.0f, 0.01f, "s", 2, 0, NULL },
    { "Pre Delay", NANO_PARAM_RANGE, 1.0f, 100.0f, 0.1f, "ms", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 800.0f, 12000.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Damping", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
};
static const nano_param_t m8007_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Decay", NANO_PARAM_RANGE, 1.0f, 10.0f, 0.01f, "s", 2, 0, NULL },
    { "Pre Delay", NANO_PARAM_RANGE, 1.0f, 200.0f, 0.1f, "ms", 1, 0, NULL },
    { "Mod Speed", NANO_PARAM_RANGE, 0.1f, 5.0f, 0.01f, "Hz", 2, 0, NULL },
    { "Mod Depth", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 800.0f, 12000.0f, 1.0f, "Hz", 0, 0, NULL },
};
static const nano_param_t m8000_params[] = {
    { "Mix", NANO_PARAM_RANGE, 0.0f, 100.0f, 0.1f, "%", 1, 0, NULL },
    { "Decay", NANO_PARAM_RANGE, 0.1f, 2.0f, 0.01f, "s", 2, 0, NULL },
    { "Pre Delay", NANO_PARAM_RANGE, 1.0f, 100.0f, 0.1f, "ms", 1, 0, NULL },
    { "High Pass", NANO_PARAM_RANGE, 20.0f, 800.0f, 1.0f, "Hz", 0, 0, NULL },
    { "Low Pass", NANO_PARAM_RANGE, 800.0f, 12000.0f, 1.0f, "Hz", 0, 0, NULL },
};

const nano_fx_model_t NANO_FX_MODELS[] = {
    { 18, "Chief BD2", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 3, m18_params, NULL },
    { 13, "Chief OD1", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 2, m13_params, NULL },
    { 6, "Exotic", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 4, m6_params, NULL },
    { 3007, "Exotic Bass Z Boost", NANO_ICON_BASS_OVERDRIVE, 0xFF7000, -1, 4, m3007_params, NULL },
    { 23, "Exotic Z Boost", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 4, m23_params, NULL },
    { 22, "Facial Fuzz", NANO_ICON_FUZZ, 0xFF7000, -1, 4, m22_params, NULL },
    { 27, "Green 808", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 3, m27_params, NULL },
    { 3000, "Microtubes B3K", NANO_ICON_BASS_OVERDRIVE, 0xFF7000, -1, 6, m3000_params, NULL },
    { 3, "OD250", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 2, m3_params, NULL },
    { 2, "Obsessive Drive", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 4, m2_params, NULL },
    { 4, "Rodent Drive", NANO_ICON_OVERDRIVE, 0xFF7000, -1, 3, m4_params, NULL },
    { 16001, "Adaptive Gate", NANO_ICON_GATE, 0xE6E6E6, -1, 1, m16001_params, NULL },
    { 4005, "Graphic 9", NANO_ICON_EQUALIZER, 0x0A74E0, -1, 12, m4005_params, NULL },
    { 4003, "Low-High Cut", NANO_ICON_EQUALIZER, 0x0A74E0, -1, 5, m4003_params, NULL },
    { 4001, "Parametric 3", NANO_ICON_EQUALIZER, 0x0A74E0, -1, 16, m4001_params, NULL },
    { 16002, "Utility Gate", NANO_ICON_GATE, 0xE6E6E6, -1, 5, m16002_params, NULL },
    { 16006, "Volume", NANO_ICON_UTILITY, 0xE6E6E6, -1, 2, m16006_params, NULL },
    { 9012, "Bass Wah", NANO_ICON_WAH, 0xE6E6E6, -1, 1, m9012_params, NULL },
    { 9010, "Bubba Wah", NANO_ICON_WAH, 0xE6E6E6, -1, 1, m9010_params, NULL },
    { 9014, "Crying Clyde Wah", NANO_ICON_WAH, 0xE6E6E6, -1, 1, m9014_params, NULL },
    { 9013, "Crying Wah", NANO_ICON_WAH, 0xE6E6E6, -1, 1, m9013_params, NULL },
    { 24006, "Envelope Filter", NANO_ICON_FILTER, 0x87DAFF, 8, 9, m24006_params, NULL },
    { 24001, "Love Meat", NANO_ICON_FILTER, 0x87DAFF, -1, 11, m24001_params, NULL },
    { 5001, "Legendary 87 (M)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5001_params, NULL },
    { 5007, "Opto Comp (M)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5007_params, NULL },
    { 5004, "Solid State Comp (M)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5004_params, NULL },
    { 5005, "VCA Comp (M)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5005_params, NULL },
    { 18001, "Transpose", NANO_ICON_PITCH, 0xFFD236, 0, 5, m18001_params, NULL },
    { 16011, "Doubler", NANO_ICON_DOUBLER, 0xE6E6E6, -1, 3, m16011_params, NULL },
    { 5012, "Legendary 87 (ST)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5012_params, NULL },
    { 5015, "Opto Comp (ST)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5015_params, NULL },
    { 5013, "Solid State Comp (ST)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5013_params, NULL },
    { 5014, "VCA Comp (ST)", NANO_ICON_COMPRESSOR, 0x45F862, 5, 6, m5014_params, NULL },
    { 7024, "Chief CE2W (ST)", NANO_ICON_MODULATION, 0x5A2CFF, 0, 8, m7024_params, m7024_order },
    { 7027, "Chief DC2W (ST)", NANO_ICON_MODULATION, 0x5A2CFF, 0, 5, m7027_params, NULL },
    { 7023, "Chorus 229T", NANO_ICON_MODULATION, 0x5A2CFF, 0, 7, m7023_params, m7023_order },
    { 7022, "Dream Chorus", NANO_ICON_MODULATION, 0x5A2CFF, 0, 7, m7022_params, m7022_order },
    { 7021, "MX Flanger", NANO_ICON_MODULATION, 0x5A2CFF, 0, 8, m7021_params, m7021_order },
    { 7028, "MX Phase 95", NANO_ICON_MODULATION, 0x5A2CFF, 0, 7, m7028_params, m7028_order },
    { 7029, "MX Vibe", NANO_ICON_MODULATION, 0x5A2CFF, 0, 8, m7029_params, m7029_order },
    { 7004, "Tremolo", NANO_ICON_MODULATION, 0x5A2CFF, -1, 12, m7004_params, m7004_order },
    { 6010, "Analog Delay", NANO_ICON_DELAY, 0x00FFDD, 0, 12, m6010_params, m6010_order },
    { 6015, "Circular Delay", NANO_ICON_DELAY, 0x00FFDD, 0, 12, m6015_params, m6015_order },
    { 6011, "Digital Delay (ST)", NANO_ICON_DELAY, 0x00FFDD, 0, 18, m6011_params, m6011_order },
    { 6012, "Dual Delay", NANO_ICON_DELAY, 0x00FFDD, 0, 22, m6012_params, m6012_order },
    { 6014, "Dual Reverse Delay", NANO_ICON_DELAY, 0x00FFDD, 0, 22, m6014_params, m6014_order },
    { 6004, "Tape Delay", NANO_ICON_DELAY, 0x00FFDD, 0, 11, m6004_params, m6004_order },
    { 8008, "Ambience", NANO_ICON_REVERB, 0x00FFDD, 0, 5, m8008_params, NULL },
    { 8009, "Cave", NANO_ICON_REVERB, 0x00FFDD, 0, 6, m8009_params, NULL },
    { 8003, "Hall", NANO_ICON_REVERB, 0x00FFDD, 0, 5, m8003_params, NULL },
    { 8011, "Mind Hall", NANO_ICON_REVERB, 0x00FFDD, 0, 6, m8011_params, NULL },
    { 8007, "Modulated", NANO_ICON_REVERB, 0x00FFDD, 0, 7, m8007_params, NULL },
    { 8000, "Room", NANO_ICON_REVERB, 0x00FFDD, 0, 5, m8000_params, NULL },
};
const unsigned NANO_FX_MODEL_COUNT = sizeof(NANO_FX_MODELS) / sizeof(NANO_FX_MODELS[0]);

static const uint32_t NANO_SLOT0_MODELS[] = { 18, 13, 6, 3007, 23, 22, 27, 3000, 3, 2, 4, 16001, 4005, 4003, 4001, 16002, 16006, 9012, 9010, 9014, 9013, 24006, 24001, 5001, 5007, 5004, 5005, 18001 };
static const uint32_t NANO_SLOT1_MODELS[] = { 18, 13, 6, 3007, 23, 22, 27, 3000, 3, 2, 4, 16001, 4005, 4003, 4001, 16002, 16006, 9012, 9010, 9014, 9013, 24006, 24001, 5001, 5007, 5004, 5005, 18001 };
static const uint32_t NANO_SLOT2_MODELS[] = { 16011, 4005, 4003, 4001, 5012, 5015, 5013, 5014, 7024, 7027, 7023, 7022, 7021, 7028, 7029, 7004 };
static const uint32_t NANO_SLOT3_MODELS[] = { 4005, 4003, 4001, 5012, 5015, 5013, 5014, 6010, 6015, 6011, 6012, 6014, 6004 };
static const uint32_t NANO_SLOT4_MODELS[] = { 4005, 4003, 4001, 5012, 5015, 5013, 5014, 8008, 8009, 8003, 8011, 8007, 8000 };
const uint32_t *const NANO_SLOT_MODELS[5] = { NANO_SLOT0_MODELS, NANO_SLOT1_MODELS, NANO_SLOT2_MODELS, NANO_SLOT3_MODELS, NANO_SLOT4_MODELS };
const uint8_t NANO_SLOT_MODEL_COUNT[5] = { 28, 28, 16, 13, 13 };
