// Generated by tools/gen_pedals.py - do not edit.
// Published version: no pedal pictures (the own build uses main/private/fx_pedals_private.c).
#include "fx_pedals.h"

static const struct { uint32_t type; const lv_image_dsc_t *image, *tile; } PEDALS[] = {
    { 0, NULL, NULL },
};

const lv_image_dsc_t *nano_fx_pedal(uint32_t type)
{
    for (size_t i = 0; type && i < sizeof(PEDALS) / sizeof(PEDALS[0]); i++) {
        if (PEDALS[i].type == type) return PEDALS[i].image;
    }
    return NULL;
}

const lv_image_dsc_t *nano_fx_pedal_tile(uint32_t type)
{
    for (size_t i = 0; type && i < sizeof(PEDALS) / sizeof(PEDALS[0]); i++) {
        if (PEDALS[i].type == type) return PEDALS[i].tile;
    }
    return NULL;
}
