// Pedal pictures (A8 masks): silhouettes for the FX editor, line drawings for the FX tiles.
// fx_pedals.c is generated by tools/gen_pedals.py from private pictures; without them it has no entries.
#pragma once

#include <stdint.h>

#include "lvgl.h"

// Picture of a model (FxTypeValue type), NULL if there is none.
const lv_image_dsc_t *nano_fx_pedal(uint32_t type);

// Line drawing of the pedal for the FX tiles (cropped at the tile's right edge), NULL if there is none.
const lv_image_dsc_t *nano_fx_pedal_tile(uint32_t type);
