// Generated by tools/preset_icons.py - do not edit.
// Symbols for the own banks; index 0 in the bank data means "no symbol", n means PRESET_ICONS[n - 1].
#pragma once

#include "lvgl.h"

#define PRESET_ICON_COUNT 19

typedef struct {
    const char *name;
    const lv_image_dsc_t *image;
} ui_preset_icon_t;

extern const ui_preset_icon_t PRESET_ICONS[PRESET_ICON_COUNT];
