// Generated by tools/gen_ui_icons.py - do not edit. UI symbols in the desktop editor's drawings.
#pragma once

#include "lvgl.h"

enum {
    UI_ICON_REFRESH,
    UI_ICON_VOLUME,
    UI_ICON_MIDI,
    UI_ICON_USB,
    UI_ICON_SAVE,
    UI_ICON_CLOSE,
    UI_ICON_CAP_AMP_HEAD,
    UI_ICON_CAP_AMP_COMBO,
    UI_ICON_CAP_AMP_CAB,
    UI_ICON_CAP_CAB,
    UI_ICON_CAP_PEDAL,
    UI_ICON_CAP_OVERDRIVE,
    UI_ICON_BACK,
    UI_ICON_CHEVRON_DOWN,
    UI_ICON_PLUS,
    UI_ICON_SCENES,
    UI_ICON_EXP,
    UI_ICON_COUNT
};

extern const lv_image_dsc_t *const UI_ICONS[UI_ICON_COUNT];
