#!/usr/bin/env python3
"""Generates main/fx_models.h/.c and the effect icons from the editor's data.

- tools/editor_models.json: FX models, parameters and slot lists exported from the Nano Cortex Editor
  (state.blocks[...].models with fxStyle() icons).
- tools/fx_icon_drawings.py: own icon drawings -> main/fx_icons.c (published).
- ../nano-cortex-editor/img/icons.css: an optional private icon set (base64 PNG masks) for the own build only
  -> main/private/fx_icons_private.c, which the build prefers and git ignores.

Run from the project folder:  python3 tools/gen_tables.py
"""
import base64
import io
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODELS = json.loads((ROOT / 'tools' / 'editor_models.json').read_text())
def find_editor():
    """The Nano Cortex Editor folder next to this project or further up (its img/ holds the private artwork)."""
    for folder in ROOT.parents:
        if (folder / 'nano-cortex-editor').is_dir():
            return folder / 'nano-cortex-editor'
    return ROOT.parent / 'nano-cortex-editor'


ICONS_CSS = find_editor() / 'img' / 'icons.css'
ICON_SIZE = 36

ICON_KEYS = ['overdrive', 'bass-overdrive', 'fuzz', 'compressor', 'equalizer', 'filter', 'wah', 'utility',
             'gate', 'doubler', 'pitch', 'modulation', 'delay', 'reverb', 'capture', 'cab', 'tuner']
AMP_W, AMP_H = 560, 124
# Category colours of the editor (FX_COLORS); modulation a little lighter so it reads on the LCD.
ICON_COLORS = {
    'overdrive': 0xFF7000, 'bass-overdrive': 0xFF7000, 'fuzz': 0xFF7000, 'compressor': 0x45F862,
    'equalizer': 0x0A74E0, 'filter': 0x87DAFF, 'wah': 0xE6E6E6, 'utility': 0xE6E6E6, 'gate': 0xE6E6E6,
    'doubler': 0xE6E6E6, 'pitch': 0xFFD236, 'modulation': 0x5A2CFF, 'delay': 0x00FFDD, 'reverb': 0x00FFDD,
}
SLOT_KEYS = ['pre1', 'pre2', 'post1', 'post2', 'post3']


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def c_ident(s):
    return re.sub(r'[^0-9a-zA-Z]+', '_', s).strip('_').lower()


def gen_models():
    out = ['// Generated by tools/gen_tables.py from tools/editor_models.json - do not edit.',
           '// FX models of the Nano Cortex with their parameters, as defined in the Nano Cortex Editor.',
           '// The type is the varint value the Nano uses for the model (StateResponse 48-52, FxTypeValue).',
           '#pragma once', '#include <stdint.h>', '',
           'typedef enum { NANO_PARAM_RANGE, NANO_PARAM_ENUM } nano_param_kind_t;', '',
           'typedef struct {',
           '    const char *name;',
           '    uint8_t kind;',
           '    float min, max, step;      // range parameters',
           '    const char *unit;',
           '    int8_t decimals;',
           '    uint8_t option_count;      // enum parameters',
           '    const char *options;       // enum options separated by "\\n" (LVGL dropdown format)',
           '} nano_param_t;', '',
           'typedef struct {',
           '    uint32_t type;',
           '    const char *name;',
           '    uint8_t icon;              // NANO_ICON_*',
           '    uint32_t color;',
           '    int8_t mix_param;          // index of the "Mix" parameter, -1 if none',
           '    uint8_t param_count;',
           '    const nano_param_t *params;',
           '    const uint8_t *order;      // display order of the parameters (indexes), NULL = as defined',
           '} nano_fx_model_t;', '',
           'enum {']
    out += ['    NANO_ICON_%s,' % c_ident(k).upper() for k in ICON_KEYS]
    out += ['    NANO_ICON_COUNT', '};', '',
            'extern const nano_fx_model_t NANO_FX_MODELS[];',
            'extern const unsigned NANO_FX_MODEL_COUNT;', '',
            '// Models available per FX slot (Pre FX 1, Pre FX 2, Post FX 1-3), in the editor\'s order.',
            'extern const uint32_t *const NANO_SLOT_MODELS[5];',
            'extern const uint8_t NANO_SLOT_MODEL_COUNT[5];', '']
    (ROOT / 'main' / 'fx_models.h').write_text('\n'.join(out))

    out = ['// Generated by tools/gen_tables.py from tools/editor_models.json - do not edit.',
           '#include "fx_models.h"', '#include <stddef.h>', '']
    for m in MODELS['models']:
        mtype, name, icon, order, params = m
        ident = 'm%d' % mtype
        rows = []
        for p in params:
            if p[1] == 'e':
                opts = p[2]
                rows.append('    { %s, NANO_PARAM_ENUM, 0, 0, 0, "", 0, %d, %s },' % (c_str(p[0]), len(opts), c_str('\n'.join(opts)).replace('\n', '\\n')))
            else:
                _, _, mn, mx, step, unit, dec = p
                rows.append('    { %s, NANO_PARAM_RANGE, %sf, %sf, %sf, %s, %d, 0, NULL },' % (c_str(p[0]), float(mn), float(mx), float(step), c_str(unit), int(dec)))
        out.append('static const nano_param_t %s_params[] = {' % ident)
        out += rows
        out.append('};')
        if order:
            out.append('static const uint8_t %s_order[] = { %s };' % (ident, ', '.join(str(i) for i in order)))
    out += ['', 'const nano_fx_model_t NANO_FX_MODELS[] = {']
    for m in MODELS['models']:
        mtype, name, icon, order, params = m
        ident = 'm%d' % mtype
        mix = next((i for i, p in enumerate(params) if p[0].lower() == 'mix'), -1)
        out.append('    { %d, %s, NANO_ICON_%s, 0x%06X, %d, %d, %s_params, %s },' % (
            mtype, c_str(name), c_ident(icon).upper(), ICON_COLORS[icon], mix, len(params), ident,
            ident + '_order' if order else 'NULL'))
    out += ['};', 'const unsigned NANO_FX_MODEL_COUNT = sizeof(NANO_FX_MODELS) / sizeof(NANO_FX_MODELS[0]);', '']
    for i, key in enumerate(SLOT_KEYS):
        out.append('static const uint32_t NANO_SLOT%d_MODELS[] = { %s };' % (i, ', '.join(str(t) for t in MODELS['slots'][key])))
    out.append('const uint32_t *const NANO_SLOT_MODELS[5] = { %s };' % ', '.join('NANO_SLOT%d_MODELS' % i for i in range(5)))
    out.append('const uint8_t NANO_SLOT_MODEL_COUNT[5] = { %s };' % ', '.join(str(len(MODELS['slots'][k])) for k in SLOT_KEYS))
    out.append('')
    (ROOT / 'main' / 'fx_models.c').write_text('\n'.join(out))


def a8_image(ident, data, w, h, static=True):
    out = ['static const uint8_t %s_map[] = {' % ident.lower()]
    for i in range(0, len(data), 24):
        out.append('    ' + ', '.join('0x%02X' % b for b in data[i:i + 24]) + ',')
    out += ['};',
            '%sconst lv_image_dsc_t %s = {' % ('static ' if static else '', ident),
            '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = %d, .h = %d, .stride = %d },' % (w, h, w),
            '    .data_size = sizeof(%s_map),' % ident.lower(),
            '    .data = %s_map,' % ident.lower(),
            '};', '']
    return out


def amp_silhouette():
    """A generic amp head, drawn here (no brand): handle, cabinet, control strip with knobs, lamp, grille."""
    from PIL import Image, ImageDraw
    k = 3   # supersampling
    img = Image.new('L', (AMP_W * k, AMP_H * k), 0)
    d = ImageDraw.Draw(img)
    S = lambda *v: [x * k for x in v]
    d.rounded_rectangle(S(236, 2, 324, 22), radius=8 * k, outline=150, width=6 * k)          # handle
    d.rounded_rectangle(S(4, 16, 556, 120), radius=16 * k, fill=40, outline=160, width=4 * k)  # cabinet
    d.rounded_rectangle(S(18, 28, 542, 58), radius=6 * k, fill=80)                            # control strip
    for i in range(7):                                                                         # knobs
        x = 112 + i * 56
        d.ellipse(S(x - 10, 33, x + 10, 53), fill=210)
        d.line(S(x, 43, x + 5, 36), fill=60, width=2 * k)
    d.ellipse(S(493, 36, 507, 50), fill=235)                                                   # lamp
    for x in (36, 62):                                                                         # input jacks
        d.ellipse(S(x - 6, 37, x + 6, 49), fill=200)
    d.rounded_rectangle(S(18, 66, 542, 108), radius=6 * k, fill=55)                            # grille
    for x in range(-40, 560, 9):                                                               # grille weave
        d.line(S(max(18, x), 66 + max(0, 18 - x), min(542, x + 42), 108), fill=95, width=1 * k)
    d.rounded_rectangle(S(18, 66, 542, 108), radius=6 * k, outline=130, width=2 * k)
    d.rounded_rectangle(S(244, 77, 316, 95), radius=4 * k, fill=150)                           # blank name plate
    return img.resize((AMP_W, AMP_H), Image.LANCZOS).tobytes()


def write_icons(path, masks, comment):
    """masks: icon key -> A8 bytes (ICON_SIZE x ICON_SIZE)."""
    out = ['// Generated by tools/gen_tables.py - do not edit.', comment,
           '// They are drawn in the colour set with the image_recolor style.',
           '#include "fx_icons.h"', '']
    names = []
    for key in ICON_KEYS:
        ident = 'icon_' + c_ident(key)
        names.append(ident if key in masks else 'NULL')
        if key not in masks:
            continue
        data = masks[key]
        out.append('static const uint8_t %s_map[] = {' % ident)
        for i in range(0, len(data), 24):
            out.append('    ' + ', '.join('0x%02X' % b for b in data[i:i + 24]) + ',')
        out += ['};',
                'static const lv_image_dsc_t %s = {' % ident,
                '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = %d, .h = %d, .stride = %d },' % (ICON_SIZE, ICON_SIZE, ICON_SIZE),
                '    .data_size = sizeof(%s_map),' % ident,
                '    .data = %s_map,' % ident,
                '};', '']
    out.append('const lv_image_dsc_t *const NANO_ICONS[NANO_ICON_COUNT] = {')
    out += ['    %s,' % ('&' + n if n != 'NULL' else 'NULL') for n in names]
    out += ['};', '']
    out += a8_image('NANO_AMP_SILHOUETTE', amp_silhouette(), AMP_W, AMP_H, static=False)
    path.parent.mkdir(exist_ok=True)
    path.write_text('\n'.join(out))
    return sum(n != 'NULL' for n in names)


def gen_icons():
    """Public icons from the own drawings; private ones too if the private icon set is there."""
    from svg_render import render
    from fx_icon_drawings import ICONS
    public = {key: render(ICONS[key], ICON_SIZE, 1.6).tobytes() for key in ICON_KEYS if key in ICONS}
    count = write_icons(ROOT / 'main' / 'fx_icons.c', public,
                        '// Effect icons (own drawings, tools/fx_icon_drawings.py) as LVGL A8 masks.')
    if not ICONS_CSS.exists():
        return count
    from PIL import Image
    css = ICONS_CSS.read_text()
    private = {}
    for key in ICON_KEYS:
        m = re.search(r'--ico-%s:\s*url\("data:image/png;base64,([^"]+)"\)' % re.escape(key), css)
        if m:
            img = Image.open(io.BytesIO(base64.b64decode(m.group(1)))).convert('RGBA')
            private[key] = img.getchannel('A').resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS).tobytes()
    write_icons(ROOT / 'main' / 'private' / 'fx_icons_private.c', private,
                '// PRIVATE - do not publish: effect icons from the own icon set (nano-cortex-editor/img/icons.css).')
    return count


gen_models()
print('fx_models.h/.c:', len(MODELS['models']), 'models')
print('fx_icons.c:', gen_icons(), 'icons' + (' (+ private set)' if ICONS_CSS.exists() else ''))
