#!/usr/bin/env python3
"""Generates main/fx_pedals.c: pedal silhouettes for the background of the FX editor and line drawings
of the pedals for the FX tiles.

The pictures are the private ones of the Nano Cortex Editor (../nano-cortex-editor/img, matched to the models
with the editor's MODEL_IMAGES table). They show third-party pedals, so they go into main/private/fx_pedals_private.c
(own build only, ignored by git). main/fx_pedals.c, the published version, has no pictures.

Run from the project folder:  python3 tools/gen_pedals.py
"""
import json
import pathlib
import re

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageOps

ROOT = pathlib.Path(__file__).resolve().parent.parent
EDITOR = None   # set below
MODELS = json.loads((ROOT / 'tools' / 'editor_models.json').read_text())
BOX = (320, 330)   # largest size on the screen (px)
TILE_H, TILE_VISIBLE, TILE_RADIUS = 124, 0.58, 12   # tile drawing: height, visible part, corner of the tile


def find_editor():
    """The Nano Cortex Editor folder next to this project or further up (its img/ holds the private artwork)."""
    for folder in ROOT.parents:
        if (folder / 'nano-cortex-editor').is_dir():
            return folder / 'nano-cortex-editor'
    return ROOT.parent / 'nano-cortex-editor'


EDITOR = find_editor()


def model_images():
    html = (EDITOR / 'index.html').read_text()
    table = re.search(r'const MODEL_IMAGES = \{(.*?)\};', html, re.S)
    return dict(re.findall(r"'([^']+)':\s*'img/([^']+)'", table.group(1))) if table else {}


def silhouette(path):
    """Grey levels of the picture inside its outline (never fully transparent there), as an A8 mask."""
    im = Image.open(path).convert('RGBA')
    im.thumbnail(BOX, Image.LANCZOS)
    lum = ImageOps.autocontrast(ImageOps.grayscale(im.convert('RGB')), cutoff=1)
    shade = Image.eval(lum, lambda v: int(70 + 185 * (v / 255) ** 0.9))
    return Image.composite(shade, Image.new('L', im.size, 0), im.getchannel('A'))


def line_drawing(path):
    """Outline and details (knobs, lettering) of the pedal, cropped at the tile's right edge, as an A8 mask."""
    im = Image.open(path).convert('RGBA')
    im.thumbnail(BOX, Image.LANCZOS)
    alpha = im.getchannel('A')
    grey = ImageOps.grayscale(im.convert('RGB'))
    edges = grey.filter(ImageFilter.GaussianBlur(0.6)).filter(ImageFilter.FIND_EDGES)
    edges = ImageOps.autocontrast(edges, cutoff=2).point(lambda v: 255 if v > 70 else int(v * 255 / 70) if v > 25 else 0)
    outline = alpha.filter(ImageFilter.FIND_EDGES).point(lambda v: 255 if v > 60 else 0).filter(ImageFilter.MaxFilter(3))
    drawing = ImageChops.lighter(ImageChops.multiply(edges, alpha), outline)
    drawing = drawing.resize((round(drawing.width * TILE_H / drawing.height), TILE_H), Image.LANCZOS)
    drawing = drawing.crop((0, 0, max(1, round(drawing.width * TILE_VISIBLE)), TILE_H))
    # Rounded corners of the tile (its right edge is the drawing's right edge; 6 px above and below).
    mask = Image.new('L', drawing.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle([-TILE_RADIUS - 2, -6, drawing.width - 1, TILE_H + 5], radius=TILE_RADIUS, fill=255)
    return ImageChops.multiply(drawing, mask)


def a8(out, ident, img):
    data = img.tobytes()
    out.append('static const uint8_t %s_map[] = {' % ident)
    for i in range(0, len(data), 32):
        out.append('    ' + ','.join('0x%02X' % b for b in data[i:i + 32]) + ',')
    out += ['};',
            'static const lv_image_dsc_t %s = {' % ident,
            '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = %d, .h = %d, .stride = %d },'
            % (img.width, img.height, img.width),
            '    .data_size = sizeof(%s_map),' % ident,
            '    .data = %s_map,' % ident,
            '};', '']


def c_ident(name):
    return re.sub(r'[^0-9a-zA-Z]+', '_', name).strip('_').lower()


def lookup_functions(out):
    for func, field in (('nano_fx_pedal', 'image'), ('nano_fx_pedal_tile', 'tile')):
        out += ['const lv_image_dsc_t *%s(uint32_t type)' % func,
                '{',
                '    for (size_t i = 0; type && i < sizeof(PEDALS) / sizeof(PEDALS[0]); i++) {',
                '        if (PEDALS[i].type == type) return PEDALS[i].%s;' % field,
                '    }',
                '    return NULL;',
                '}', '']


def write_public():
    out = ['// Generated by tools/gen_pedals.py - do not edit.',
           '// Published version: no pedal pictures (the own build uses main/private/fx_pedals_private.c).',
           '#include "fx_pedals.h"', '',
           'static const struct { uint32_t type; const lv_image_dsc_t *image, *tile; } PEDALS[] = {',
           '    { 0, NULL, NULL },', '};', '']
    lookup_functions(out)
    (ROOT / 'main' / 'fx_pedals.c').write_text('\n'.join(out))


def main():
    write_public()
    images = model_images() if (EDITOR / 'img').is_dir() else {}
    if not images:
        print('fx_pedals.c: no pictures (published version only)')
        return
    out = ['// Generated by tools/gen_pedals.py - do not edit.',
           '// PRIVATE - do not publish: third-party pedal pictures.',
           '#include "fx_pedals.h"', '']
    used = {}   # file -> identifier
    entries = []
    for model in MODELS['models']:
        type_, name = model[0], model[1]
        # Stereo / mono variants share the picture of the other one.
        file = images.get(name) or images.get(name.replace('(ST)', '(M)')) or images.get(name.replace('(M)', '(ST)'))
        if not file or not (EDITOR / 'img' / file).exists():
            continue
        if file not in used:
            ident = 'pedal_' + c_ident(pathlib.Path(file).stem)
            used[file] = ident
            a8(out, ident, silhouette(EDITOR / 'img' / file))
            a8(out, ident + '_tile', line_drawing(EDITOR / 'img' / file))
        entries.append((type_, name, used[file]))

    out.append('static const struct { uint32_t type; const lv_image_dsc_t *image, *tile; } PEDALS[] = {')
    out += ['    { %d, &%s, &%s_tile },   // %s' % (t, ident, ident, name) for t, name, ident in entries]
    out += ['};', '']
    lookup_functions(out)
    (ROOT / 'main' / 'private').mkdir(exist_ok=True)
    (ROOT / 'main' / 'private' / 'fx_pedals_private.c').write_text('\n'.join(out))
    print('fx_pedals_private.c: %d models, %d pictures (+ published fx_pedals.c without pictures)' % (len(entries), len(used)))


if __name__ == '__main__':
    main()
