#!/usr/bin/env python3
"""UI symbols of the board in the desktop editor's drawings (nano-cortex-editor/tools/icons.py, own drawings):
top bar (refresh, volume, MIDI, USB, save), dialog close, the capture types (amp head, combo, amp + cab, cab,
pedal, overdrive), the FX editor's back, chevron and plus and the scenes and expression pedal buttons. Writes main/ui_icons.c (published). With the
private icon set (nano-cortex-editor/img/icons.css) the capture types also go into main/private/ui_icons_private.c
with the original symbols (own build only).
Run from the project folder:  python3 tools/gen_ui_icons.py
"""
import base64
import importlib.util
import io
import pathlib
import re

from svg_render import render

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIZE = 36   # as the effect icons (fx_icons.c); drawn smaller with lv_image_set_scale where needed


def find_editor():
    for folder in ROOT.parents:
        if (folder / 'nano-cortex-editor').is_dir():
            return folder / 'nano-cortex-editor'
    return ROOT.parent / 'nano-cortex-editor'


EDITOR = find_editor()
spec = importlib.util.spec_from_file_location('editor_icons', EDITOR / 'tools' / 'icons.py')
editor = importlib.util.module_from_spec(spec)
spec.loader.exec_module(editor)

OWN = {   # not in the editor's set
    'volume': '<path d="M4 9.5h3.5L12 6v12l-4.5-3.5H4z"/><path d="M15.5 9.5a3.5 3.5 0 0 1 0 5"/><path d="M18 7a7 7 0 0 1 0 10"/>',
    'usb': '<path d="M12 3v14"/><path d="M9.5 5.5L12 3l2.5 2.5"/><path d="M12 14l-4.5-2.5V9"/><path d="M12 12l4.5-2.5V7.5"/>'
           '<circle cx="7.5" cy="8" r="1"/><rect x="15.5" y="6" width="2" height="2"/><circle cx="12" cy="19" r="2"/>',
    'back': '<path d="M15 5l-7 7 7 7"/>',
    'chevron-down': '<path d="M6 9l6 6 6-6"/>',
    'plus': '<path d="M12 5v14M5 12h14"/>',
    'scenes': '<path d="M12 4l8 4.3-8 4.3-8-4.3z"/><path d="M4 12.3l8 4.3 8-4.3"/><path d="M4 16l8 4.3 8-4.3"/>',
}
KEYS = ['refresh', 'volume', 'midi', 'usb', 'save', 'close',
        'cap-amp-head', 'cap-amp-combo', 'cap-amp-cab', 'cap-cab', 'cap-pedal', 'cap-overdrive',
        'back', 'chevron-down', 'plus',   # FX editor
        'scenes', 'exp']                  # scenes and expression pedal buttons
CAPTURE_KEYS = KEYS[6:12]


def c_ident(key):
    return re.sub(r'[^0-9a-z]+', '_', key)


def write(path, masks, comment):
    out = ['// Generated by tools/gen_ui_icons.py - do not edit.', comment,
           '// A8 masks (%dx%d), drawn in the colour set with the image_recolor style.' % (SIZE, SIZE), '#include "ui_icons.h"', '']
    for key in KEYS:
        data = masks[key]
        ident = 'ui_icon_' + c_ident(key)
        out.append('static const uint8_t %s_map[] = {' % ident)
        for i in range(0, len(data), 24):
            out.append('    ' + ', '.join('0x%02X' % b for b in data[i:i + 24]) + ',')
        out += ['};', 'static const lv_image_dsc_t %s = {' % ident,
                '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = %d, .h = %d, .stride = %d },' % (SIZE, SIZE, SIZE),
                '    .data_size = sizeof(%s_map),' % ident, '    .data = %s_map,' % ident, '};', '']
    out.append('const lv_image_dsc_t *const UI_ICONS[UI_ICON_COUNT] = {')
    out += ['    &ui_icon_%s,' % c_ident(k) for k in KEYS]
    out += ['};', '']
    path.parent.mkdir(exist_ok=True)
    path.write_text('\n'.join(out))


def main():
    drawings = dict(editor.ICONS, **OWN)
    public = {key: render(drawings[key], SIZE, 1.3).tobytes() for key in KEYS}
    header = ['// Generated by tools/gen_ui_icons.py - do not edit. UI symbols in the desktop editor\'s drawings.',
              '#pragma once', '', '#include "lvgl.h"', '', 'enum {']
    header += ['    UI_ICON_%s,' % c_ident(k).upper() for k in KEYS]
    header += ['    UI_ICON_COUNT', '};', '', 'extern const lv_image_dsc_t *const UI_ICONS[UI_ICON_COUNT];', '']
    (ROOT / 'main' / 'ui_icons.h').write_text('\n'.join(header))
    write(ROOT / 'main' / 'ui_icons.c', public, '// Own drawings (the desktop editor\'s tools/icons.py), published.')
    css_path = EDITOR / 'img' / 'icons.css'
    if css_path.exists():
        from PIL import Image
        css = css_path.read_text()
        private = dict(public)
        for key in CAPTURE_KEYS:
            m = re.search(r'--ico-%s:\s*url\("data:image/png;base64,([^"]+)"\)' % re.escape(key), css)
            if m:
                img = Image.open(io.BytesIO(base64.b64decode(m.group(1)))).convert('RGBA')
                private[key] = img.getchannel('A').resize((SIZE, SIZE), Image.LANCZOS).tobytes()
        write(ROOT / 'main' / 'private' / 'ui_icons_private.c', private,
              '// PRIVATE - do not publish: capture type symbols from the own icon set (nano-cortex-editor/img/icons.css).')
        print('ui_icons.c + private set (%d capture symbols)' % sum(private[k] != public[k] for k in CAPTURE_KEYS))
    else:
        print('ui_icons.c (public only)')


if __name__ == '__main__':
    main()
